language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $COMPOSER_CACHE_DIR

php:
  - 7.1
  - 7.2

stages:
  - test
  - test code coverage
  - release deploy
  - dist deploy
  - docs deploy

before_install:
  - composer self-update
  - if [[ $TEST_COVERAGE != true ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  #- travis_retry composer install -n --prefer-source
  #- if [[ $TEST_COVERAGE == true ]]; then travis_retry composer test-coverage-install || return 0 ; fi
  - echo "COMPOSER INSTALL"

#script: composer test
script: echo "RUN TEST SCRIPT"

jobs:
  allow_failures:
    - php: 7.2
  include:
    - stage: test code coverage
      php: 7.1
      if: (NOT type IN (pull_request)) AND (branch = master)
      env:
        - TEST=true
        - TEST_COVERAGE=true
      before_script:
        - mkdir -p build/logs
      script:
        #- travis_retry composer test-coverage
        - echo "RUN TEST COVERAGE"
      after_success:
        #- travis_retry composer test-coverage-upload
        - echo "UPLOAD TEST COVERAGE"
        - bash <(curl -s https://codecov.io/bash)

    - stage: docs deploy
      #if: (tags = true) AND (branch = master)
      install: skip
      script: skip
      deploy:
        provider: script
        script: bash scripts/deploy-docs.sh
        skip_cleanup: true
        overwrite: true
        on:
          branch: master
          php: "7.1"

    - stage: release deploy
      if: (tags = true) AND (branch = master)
      install: skip
      script: skip
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file: "dist/cecil.phar"
        skip_cleanup: true
        overwrite: true
        on:
          tags: true
          php: "7.1"

    - stage: dist deploy
      if: (tags = true) AND (branch = master)
      install: skip
      script: skip
      deploy:
        provider: script
        script: bash scripts/deploy-dist.sh
        skip_cleanup: true
        overwrite: true
        on:
          tags: true
          php: "7.1"
